### ISSUE TITLE
How to get detailed text prompt

### ISSUE THREAD

**Issue by 02w20** [shallowdream204/DreamClear#2]
Hello! Thanks for your work. But I have doubts about the generation of text prompts, Hope you can help me.

When reading the paper, I thought it was obtained by using the rough intermediate results obtained from swinIR as input for LLaVA. But I didn't see any similar code in the code, I only saw something like reading a file to get text_info. So I'm curious if the text prompt was obtained in advance through the ground truth as input？If that's the case, how can we obtain a text prompt during the inference phase when the ground truth is unknown？

Look forward to your reply, thanks!

**Comment by shallowdream204** [comment]
Your understanding is correct. During the inference stage, we use the output of SwinIR as the input for LLaVA to get the text prompts. We do not use any GT images during inference. In fact, for benchmarks like RealLQ250, there are no GT images at all. In the npz folder that we provide for RealLQ250, we store the text features that have been extracted by T5. Due to the upcoming CVPR submission deadline, we will update the more generalized inference code as soon as possible for your use. Thank you for your understanding.

**Comment by 02w20** [comment]
谢谢你的及时回复！也就是说目前仓库里还没有将SwimIR结果作为LLaVA输入的这部分代码？

**Comment by shallowdream204** [comment]
是的，我们在实验过程中为了便于快速测试，首先使用 SwinIR 预处理图像，然后通过 Llava 生成图像描述，得到文本提示。接下来，我们使用 T5 提取特征并将其存储在硬盘上。我们会尽快将这一流程更新到推理代码中，临近CVPR ddl有些忙，谢谢理解～
